import {
  cilUser,
  cilUserPlus,
  cilSpeedometer,
  cilPeople,
  cilLayers,
  cilList,
  cilNotes,
  cilContact,
  cilMenu,
  cilEnvelopeOpen,
  cilCommentSquare,
  cilSettings,
  cilAccountLogout,
  cilLibraryAdd,
  cilSortAscending,
  cilSortDescending,
  cilCheckCircle,  
  cilXCircle,
  cilPenAlt,
  cilTrash,
  cilChevronCircleLeftAlt,
  cilChevronCircleRightAlt,  
} from '@coreui/icons';

export const iconSubset = {
  cilUser,
  cilUserPlus,
  cilSpeedometer,
  cilPeople,
  cilLayers,
  cilList,
  cilNotes,
  cilContact,
  cilMenu,
  cilEnvelopeOpen,
  cilCommentSquare,
  cilSettings,
  cilAccountLogout,
  cilLibraryAdd,
  cilSortAscending,
  cilSortDescending,
  cilCheckCircle,
  cilXCircle,
  cilPenAlt,
  cilTrash,
  cilChevronCircleLeftAlt,
  cilChevronCircleRightAlt,
};

export enum IconSubset {
  
}
